export const validateProductionOrderSequence = async (
  conn,
  {
    factoryId,
    productId,
    lineId,
    stageId,
    scannedValue,
    isCustomerQrScan = false,
    productionOrderId = null,
    customerQr = null,
  }
) => {
  const normalizedScannedValue = String(scannedValue || "").trim();

  if (!normalizedScannedValue) {
    return {
      ok: false,
      errorType: "INVALID_SERIAL",
      message: "Scanned serial number is required.",
    };
  }

  // ============================================================
  // 1. Validate physical station
  // ============================================================

  const [stationRows] = await conn.query(
    `
    SELECT id, name
    FROM stages
    WHERE id = ?
      AND line_id = ?
      AND factory_id = ?
      AND is_active = 1
    LIMIT 1
    `,
    [stageId, lineId, factoryId]
  );

  if (!stationRows.length) {
    return {
      ok: false,
      errorType: "INVALID_STATION",
      message:
        "This stage is not active or does not belong to the current production line.",
    };
  }

  // ============================================================
  // 2. Resolve identity
  // ============================================================

  let resolvedProductQr = normalizedScannedValue;
  const scanIdentityType = isCustomerQrScan ? "CUSTOMER_QR" : "PRODUCT_QR";
  let customerBinding = null;
  let resolvedCustomerQr = customerQr ? String(customerQr).trim() : null;

  // ============================================================
  // 2A. Customer QR
  // ============================================================

  if (isCustomerQrScan) {
    if (!resolvedCustomerQr) {
      return {
        ok: false,
        errorType: "CUSTOMER_QR_REQUIRED",
        message: "Customer QR is required.",
      };
    }

    // ----------------------------------------------------------
    // Customer QR must exist in MES-generated Customer QR pool
    // ----------------------------------------------------------

    const [customerQrRows] = await conn.query(
      `
      SELECT
        id,
        qr_code,
        status,
        bound_at
      FROM customer_qr_codes
      WHERE qr_code = ?
      LIMIT 1
      `,
      [resolvedCustomerQr]
    );

    if (!customerQrRows.length) {
      return {
        ok: false,
        errorType: "INVALID_CUSTOMER_QR",
        message:
          `"${resolvedCustomerQr}" is not a valid Customer QR generated by SMES.`,
      };
    }

    // ----------------------------------------------------------
    // Find Customer QR binding
    // ----------------------------------------------------------

    const [bindingRows] = await conn.query(
      `
      SELECT
        id,
        pcb_qr,
        customer_qr,
        product_id,
        production_order_id,
        factory_id,
        line_id,
        stage_id
      FROM customer_bindings
      WHERE customer_qr = ?
      ORDER BY id DESC
      LIMIT 1
      `,
      [resolvedCustomerQr]
    );

    if (!bindingRows.length) {
      return {
        ok: false,
        errorType: "CUSTOMER_QR_NOT_BOUND",
        message:
          `"${resolvedCustomerQr}" is not bound to a Product QR.`,
      };
    }

    customerBinding = bindingRows[0];

    // ----------------------------------------------------------
    // Resolve Product QR
    // ----------------------------------------------------------

    resolvedProductQr = String(customerBinding.pcb_qr || "").trim();

    if (!resolvedProductQr) {
      return {
        ok: false,
        errorType: "CUSTOMER_QR_INVALID_BINDING",
        message: "This Customer QR has an invalid Product QR binding.",
      };
    }

    // ----------------------------------------------------------
    // Customer QR is tied to exact Production Order
    // ----------------------------------------------------------

    if (customerBinding.production_order_id) {
      productionOrderId = customerBinding.production_order_id;
    }
  }

  // ============================================================
  // 2B. Product QR
  // ============================================================

  if (!isCustomerQrScan) {
    const [existingBindingRows] = await conn.query(
      `
      SELECT
        id,
        customer_qr,
        product_id,
        production_order_id,
        factory_id,
        line_id
      FROM customer_bindings
      WHERE pcb_qr = ?
      ORDER BY id DESC
      LIMIT 1
      `,
      [resolvedProductQr]
    );

    if (existingBindingRows.length) {
      const binding = existingBindingRows[0];

      return {
        ok: false,
        errorType: "CUSTOMER_QR_REQUIRED",
        message:
          `This Product QR is already bound to Customer QR "${binding.customer_qr}". ` +
          `Please scan the Customer QR instead.`,
        scannedSerial: resolvedProductQr,
        productQr: resolvedProductQr,
        customerQr: binding.customer_qr,
      };
    }
  }

  // ============================================================
  // 3. Find Production Order Item
  // ============================================================

  let itemRows;

  if (productionOrderId) {
    [itemRows] = await conn.query(
      `
      SELECT
        poi.id AS item_id,
        poi.production_order_id,
        poi.serial_no,
        poi.sequence_no,
        poi.status AS item_status,

        po.order_no,
        po.factory_id,
        po.product_id,
        po.line_id,
        po.sequence_mode,
        po.status AS order_status,
        po.target_qty,
        po.serial_start,
        po.serial_end

      FROM production_order_items poi

      INNER JOIN production_orders po
        ON po.id = poi.production_order_id

      WHERE poi.production_order_id = ?
        AND poi.serial_no = ?
        AND po.factory_id = ?
        AND po.product_id = ?

      LIMIT 1
      `,
      [
        productionOrderId,
        resolvedProductQr,
        factoryId,
        productId,
        lineId,
      ]
    );
  } else {
    [itemRows] = await conn.query(
      `
      SELECT
        poi.id AS item_id,
        poi.production_order_id,
        poi.serial_no,
        poi.sequence_no,
        poi.status AS item_status,

        po.order_no,
        po.factory_id,
        po.product_id,
        po.line_id,
        po.sequence_mode,
        po.status AS order_status,
        po.target_qty,
        po.serial_start,
        po.serial_end

      FROM production_order_items poi

      INNER JOIN production_orders po
        ON po.id = poi.production_order_id

      WHERE poi.serial_no = ?
        AND po.factory_id = ?
        AND po.product_id = ?
        AND po.line_id = ?

      ORDER BY
        CASE WHEN po.status = 'RUNNING' THEN 0 ELSE 1 END,
        po.id DESC

      LIMIT 1
      `,
      [
        resolvedProductQr,
        factoryId,
        productId,
        lineId,
      ]
    );
  }

  // ============================================================
  // 4. Serial not found
  // ============================================================

  if (!itemRows.length) {
    return {
      ok: false,
      errorType: "SERIAL_NOT_IN_PRODUCTION_ORDER",
      message: isCustomerQrScan
        ? `Customer QR "${resolvedCustomerQr}" is bound to Product QR "${resolvedProductQr}", but that Product QR does not belong to the current production order.`
        : "This Serial No beyonds the production order or maybe does not belongs to this Production Order.",
      scannedSerial: normalizedScannedValue,
      resolvedProductQr,
      scanIdentityType,
      customerQr: resolvedCustomerQr,
    };
  }

  const item = itemRows[0];

  // ============================================================
  // 5. Production Order must be RUNNING
  // ============================================================

  if (item.order_status !== "RUNNING") {
    return {
      ok: false,
      errorType: "PRODUCTION_ORDER_NOT_RUNNING",
      message:
        `This serial belongs to production order ${item.order_no}, ` +
        `which is currently ${item.order_status}.`,
      productionOrderId: item.production_order_id,
    };
  }

  // ============================================================
  // 6. Rejected item
  // ============================================================

  if (item.item_status === "REJECTED") {
    return {
      ok: false,
      errorType: "SERIAL_REJECTED",
      message:
        "This product has been rejected and cannot continue production.",
      productionOrderId: item.production_order_id,
      serialNo: item.serial_no,
    };
  }

  // ============================================================
  // 7. Current Product Stage
  // ============================================================

  const [currentFlowRows] = await conn.query(
    `
    SELECT
      id,
      stage_id,
      sequence_no,
      scan_mode
    FROM product_stage_flow
    WHERE product_id = ?
      AND stage_id = ?
    LIMIT 1
    `,
    [item.product_id, stageId]
  );

  if (!currentFlowRows.length) {
    return {
      ok: false,
      errorType: "STAGE_NOT_IN_PRODUCT_FLOW",
      message:
        "This stage is not configured in the product's stage flow.",
    };
  }

  const currentStage = currentFlowRows[0];
  const currentSequence = Number(currentStage.sequence_no);

  // ============================================================
  // 8. Get Production Order Stage
  // ============================================================

  const [productionStageRows] = await conn.query(
    `
    SELECT
      id,
      production_order_id,
      stage_id,
      sequence_order,
      next_expected_sequence,
      status
    FROM production_order_stages
    WHERE production_order_id = ?
      AND stage_id = ?
    LIMIT 1
    `,
    [item.production_order_id, stageId]
  );

  if (!productionStageRows.length) {
    return {
      ok: false,
      errorType: "STAGE_NOT_IN_PRODUCTION_ORDER",
      message:
        "This stage is not configured for the production order.",
      productionOrderId: item.production_order_id,
    };
  }

  const productionOrderStage = productionStageRows[0];

  // ============================================================
  // 9. Production Order object
  // ============================================================

  const productionOrder = {
    id: item.production_order_id,
    order_no: item.order_no,
    factory_id: item.factory_id,
    product_id: item.product_id,
    line_id: item.line_id,
    target_qty: item.target_qty,
    sequence_mode: item.sequence_mode,
    status: item.order_status,
    serial_start: item.serial_start,
    serial_end: item.serial_end,
  };

  const productionOrderItem = {
    id: item.item_id,
    production_order_id: item.production_order_id,
    serial_no: item.serial_no,
    sequence_no: item.sequence_no,
    status: item.item_status,
  };

  // ============================================================
  // 10. First stage
  // ============================================================

  if (currentSequence === 1) {
    return {
      ok: true,
      productionOrder,
      productionOrderItem,
      productionOrderStage,
      productStageFlow: currentStage,
      scannedValue: normalizedScannedValue,
      scanIdentityType,
      resolvedProductQr,
      customerQr: resolvedCustomerQr,
      customerBinding,
    };
  }

  // ============================================================
  // 11. NON-SEQUENTIAL
  // ============================================================

  if (item.sequence_mode === "NON_SEQUENTIAL") {
    return {
      ok: true,
      productionOrder,
      productionOrderItem,
      productionOrderStage,
      productStageFlow: currentStage,
      scannedValue: normalizedScannedValue,
      scanIdentityType,
      resolvedProductQr,
      customerQr: resolvedCustomerQr,
      customerBinding,
    };
  }

  // ============================================================
  // 12. Find previous stage
  // ============================================================

  const previousSequence = currentSequence - 1;

  const [previousStageRows] = await conn.query(
    `
    SELECT
      id,
      stage_id,
      sequence_no,
      scan_mode
    FROM product_stage_flow
    WHERE product_id = ?
      AND sequence_no = ?
    LIMIT 1
    `,
    [item.product_id, previousSequence]
  );

  if (!previousStageRows.length) {
    return {
      ok: false,
      errorType: "PREVIOUS_STAGE_NOT_FOUND",
      message:
        `Previous stage with sequence ${previousSequence} is not configured.`,
    };
  }

  const previousStage = previousStageRows[0];

  // ============================================================
  // 13. Determine identity used by PREVIOUS stage
  // ============================================================

  let previousScanIdentity = resolvedProductQr;

  if (previousStage.scan_mode !== "CUSTOMER_BINDING") {
    const [bindingStageRows] = await conn.query(
      `
      SELECT sequence_no
      FROM product_stage_flow
      WHERE product_id = ?
        AND scan_mode = 'CUSTOMER_BINDING'
      LIMIT 1
      `,
      [item.product_id]
    );

    const bindingSequence = bindingStageRows.length
      ? Number(bindingStageRows[0].sequence_no)
      : null;

    if (
      bindingSequence !== null &&
      Number(previousStage.sequence_no) > bindingSequence
    ) {
      previousScanIdentity = resolvedCustomerQr;
    }
  }

  // ============================================================
  // 14. Previous stage must have SUCCESS
  // ============================================================

  if (!previousScanIdentity) {
    return {
      ok: false,
      errorType: "CUSTOMER_QR_REQUIRED",
      message:
        "Customer QR is required because this product has already passed the Customer Binding stage.",
    };
  }

  const [previousScanRows] = await conn.query(
    `
    SELECT
      id,
      scanned_value,
      stage_id,
      sequence_no,
      status
    FROM scan_history
    WHERE production_order_id = ?
      AND stage_id = ?
      AND scanned_value = ?
      AND status = 'SUCCESS'
    ORDER BY id DESC
    LIMIT 1
    `,
    [
      item.production_order_id,
      previousStage.stage_id,
      previousScanIdentity,
    ]
  );

  if (!previousScanRows.length) {
    return {
      ok: false,
      errorType: "PREVIOUS_STAGE_NOT_COMPLETED",
      message:
        `This item has not successfully completed the previous stage ` +
        `(${previousSequence}).`,
      productionOrderId: item.production_order_id,
      expectedSequence: previousSequence,
      expectedSerial: item.serial_no,
      scannedSequence: item.sequence_no,
      scannedSerial: normalizedScannedValue,
      previousStageId: previousStage.stage_id,
      previousStageSequence: previousStage.sequence_no,
      previousScanIdentity,
      resolvedProductQr,
      customerQr: resolvedCustomerQr,
    };
  }

  // ============================================================
  // 15. SUCCESS
  // ============================================================

  return {
    ok: true,
    productionOrder,
    productionOrderItem,
    productionOrderStage,
    productStageFlow: currentStage,

    previousStage: {
      id: previousStage.id,
      stage_id: previousStage.stage_id,
      sequence_no: previousStage.sequence_no,
      scan_mode: previousStage.scan_mode,
    },

    previousScan: previousScanRows[0],

    scannedValue: normalizedScannedValue,
    scanIdentityType,
    resolvedProductQr,
    customerQr: resolvedCustomerQr,
    customerBinding,
  };
};